# Generated by Django 4.2.2 on 2023-06-11 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='direccion',
            field=models.CharField(blank=True, max_length=100, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='servicio',
            field=models.CharField(choices=[('BARBERIA', 'Barberia'), ('MASAJES', 'Masajes'), ('PELUQUERIA', 'Peluqueria'), ('UNAS', 'Unas')], default='BARBERIA', max_length=100),
        ),
        migrations.AlterField(
            model_name='cita',
            name='tipo_identificacion',
            field=models.CharField(choices=[('CEDULA', 'Cedula'), ('IDENTIDAD', 'Tarjeta Identidad'), ('CIVIL', 'Registro Civil')], default='CEDULA', max_length=100),
        ),
    ]
