# Generated by Django 4.2.2 on 2023-06-17 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_cita_direccion_alter_cita_servicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='fecha',
            field=models.DateField(max_length=100, verbose_name='Fecha del servicio'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='hora',
            field=models.TimeField(max_length=100, verbose_name='Hora del servicio'),
        ),
    ]
