# Generated by Django 4.2.2 on 2023-06-17 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_alter_cita_fecha_alter_cita_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='servicio',
            field=models.CharField(choices=[('BARBERIA', 'Barberia'), ('MASAJES', 'Masajes'), ('PELUQUERIA', 'Peluqueria'), ('FACIAL', 'Facial'), ('UNAS', 'Unas')], default='BARBERIA', max_length=100),
        ),
    ]
